name: CI
on: 
  push
    branches: [main]
  pull_requests:
    branches: [main]
jobs:
  Lint:
    # Lint任务
  UnitTest:
    # 单元测试任务
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@2.1.0
        with:
          version: 7.2.1
      - name: Install modules
        run: pnpm install
      - name: Run Test
        run: pnpm run test:run